# Generated by Django 4.0.1 on 2022-01-26 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0002_alter_feed_number_of_rate_alter_feed_total_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRatings',
            new_name='UserRate',
        ),
    ]
